---
#- name: install required packages
#  apt:
#    name: "{{ packages }}"
#    state: present
#    dpkg_options: 'force-confnew,force-confdef'
#    autoclean: yes
#    autoremove: yes
#    update_cache: yes
#    cache_valid_time: 3600
#  vars:
#    packages:
#    - oracle-java8-installer

- name: Check if we are done
  stat:
    path: "{{ keycloak_jboss_home }}/create.done"
  register: _done_file

- block:

  - name: create keycloak user
    user:
      name: keycloak

  - name: keycloak target directory
    file:
      dest: "{{ keycloak_dir }}"
      mode: 0755
      owner: root
      group: root
      state: directory

  - name: get Keycloak distribution tarball
    get_url:
      url: "{{ keycloak_url }}"
      dest: "{{ keycloak_dir }}"

  - name: unpack keycloak
    unarchive:
      src: "{{ keycloak_dir }}/{{ keycloak_archive }}"
      dest: "{{ keycloak_dir }}"
      copy: no

  - name: keycloak log directory
    file:
      dest: "{{ keycloak_log_dir }}"
      mode: 0755
      owner: keycloak
      group: keycloak
      state: directory

  - name: keycloak data directory
    file:
      dest: "{{ keycloak_jboss_home }}/standalone/data"
      mode: 0755
      owner: keycloak
      group: keycloak
      state: directory

  - name: keycloak tmp directory
    file:
      dest: "{{ keycloak_jboss_home }}/standalone/tmp"
      mode: 0755
      owner: keycloak
      group: keycloak
      state: directory

  - name: make keycloak configuration directory readable
    file:
      dest: "{{ keycloak_jboss_home }}/standalone/configuration"
      mode: 0755
      owner: keycloak
      group: keycloak
      state: directory
      recurse: yes

  - name: keycloak systemd setup
    template:
      owner: root
      group: root
      mode: 0644
      src: keycloak.service.j2
      dest: /etc/systemd/system/keycloak.service

  - name: configure mysql usage
    include: mysql.yml
    when: keycloak_mysql

  - name: just force systemd to reread configs
    systemd:
      daemon_reload: yes

  - name: enable keycloak
    systemd:
      name: keycloak
      enabled: yes

  - name: start keycloak
    systemd:
      name: keycloak
      state: started

  - name: create admin user
    include: admin.yml
    when: keycloak_create_admin

  - name: create the finished file
    file:
      path: "{{ keycloak_jboss_home }}/create.done"
      state: touch

  when: not _done_file.stat.exists

...
